apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-postgres
spec:
  provider: azure
  parameters:
    useWorkloadIdentity: "true"
    clientID: 23f3746b-e97a-4440-ad18-c11a6281ffa7
    keyvaultName: kv-voting-app
    tenantId: 4931ba2c-07c3-4ac5-81ad-3b26c008f85d
    objects: |
      array:
        - |
          objectName: postgres-password
          objectType: secret
  secretObjects:
  - secretName: db-secret
    type: Opaque
    data:
    - objectName: postgres-password
      key: POSTGRES_PASSWORD

